# syncFiles_fastFiles.sh
# This is an example of a file generated by the rsync scripts.  It will be generated without the comments.
#
# Copyright (c) 2025 Oracle and/or its affiliates
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/ 

scp /u02/app/ebs/visprd/fs1/EBSapps/appl/INCLUDEME.txt applmgr@10.0.103.17:/u02/app/ebs/visprd/fs1/EBSapps/appl/INCLUDEME.txt
scp /u02/app/ebs/visprd/fs2/EBSapps/appl/INCLUDEME.txt applmgr@10.0.103.17:/u02/app/ebs/visprd/fs2/EBSapps/appl/INCLUDEME.txt
